### ISSUE TITLE
unable to run on android

### ISSUE THREAD

**Issue by mattfeury** [io-pan/SOL-ReactNative-0.57.1#1]
hello,

i am trying to run this project on my android and not having luck. it is erroring on this line i believe: https://github.com/io-pan/SOL-ReactNative/blob/af63dd0cecdee7bcdc72aa4893c65484654409b5/components/motion.js#L554

looking at [the docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RCTCamera.md#ios-getfov-promise), i see this is an iOS only method. (those docs are for RCTCamera. i don't see any reference of getFOV in RNCamera which you're using).

this looks like a cool project. would love any guidance on how to get it running. thanks!

**Comment by io-pan** [comment]
Hi Mattfeury,

Sorry for that late answer.
The getFOV function is not part of android-RNCamera anymore (or maybe it has never existed, I can't remember).
But I need it to properly overlay my 3D scene camera over the device camera, so I add the function.

Here is how to do it
 (sadly I did not fork RNCamera so this needs to be done each time you npm install react-native-camera)

in **SOL\node_modules\react-native-camera\android\src\main\java\com\google\android\cameraview\Camera1.java**
add 
```
    @Override
    Float getFOV() {
     return mCameraParameters.getHorizontalViewAngle();
    }
```

in **SOL\node_modules\react-native-camera\android\src\main\java\com\google\android\cameraview\Camera2.java**

```
@Override
Float getFOV() {
       float[] focalLengths = mCameraCharacteristics.get(CameraCharacteristics.LENS_INFO_AVAILABLE_FOCAL_LENGTHS);
    SizeF sensorSize = mCameraCharacteristics.get(CameraCharacteristics.SENSOR_INFO_PHYSICAL_SIZE);
    Rect activeArray = mCameraCharacteristics.get(CameraCharacteristics.SENSOR_INFO_ACTIVE_ARRAY_SIZE);
    float pixelArrayW = mCameraCharacteristics.get(CameraCharacteristics.SENSOR_INFO_PIXEL_ARRAY_SIZE).getWidth();

    float output_physical_width = sensorSize.getWidth() * activeArray.width() / pixelArrayW;

    if (focalLengths != null && focalLengths.length > 0) {
        return (float) (2.0f * Math.atan(output_physical_width / (2.0f * focalLengths[0])));
    }

    return 1.1f;
}
```

in **SOL\node_modules\react-native-camera\android\src\main\java\com\google\android\cameraview\CameraView.java**
```
    public Float getFOV() {
        return  mImpl.getFOV();
    }
```

in **SOL\node_modules\react-native-camera\android\src\main\java\com\google\android\cameraview\CameraViewImpl.java**

`abstract Float getFOV();`

in **SOL\node_modules\react-native-camera\android\src\main\java\org\reactnative\camera\CameraModule.java**

  ```@ReactMethod
  public void getFOV(final int viewTag, final Promise promise) {
      final ReactApplicationContext context = getReactApplicationContext();
      UIManagerModule uiManager = context.getNativeModule(UIManagerModule.class);
      uiManager.addUIBlock(new UIBlock() {
          @Override
          public void execute(NativeViewHierarchyManager nativeViewHierarchyManager) {
              final RNCameraView cameraView;

              try {
                  cameraView = (RNCameraView) nativeViewHierarchyManager.resolveView(viewTag);
                  WritableArray result = Arguments.createArray();
                  result.pushString(cameraView.getFOV().toString());  
                  promise.resolve(result);
              } catch (Exception e) {
                  e.printStackTrace();
                    promise.reject("E_CAMERA_UNAVAILABLE", "Camera is not running");
              }
          }
      });
  }
```

in **SOL\node_modules\react-native-camera\src\Camera.js:**
```
getFOV() {
    return CameraManager.getFOV();
}
```

and finaly in **SOL\node_modules\react-native-camera\src\RNCamera.js:**
```
 async getFOV() {
     return await CameraManager.getFOV( this._cameraHandle);
  }
```

hope it helps ... I just push the whole node_modules folder so you can find the source of my modified react-native-camera. The release APK is also on root of project.
